"""empty message

Revision ID: d6044d132219
Revises: 1cffdac340e1
Create Date: 2022-06-19 18:25:28.961340

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "d6044d132219"
down_revision = "1cffdac340e1"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("measure_name", table_name="measure")
    op.drop_index("rule_id", table_name="rule")
    op.drop_index("rule_measure_id", table_name="rule_measure")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index("rule_measure_id", "rule_measure", ["rule_id"], unique=False)
    op.create_index("rule_id", "rule", ["id"], unique=False)
    op.create_index("measure_name", "measure", ["name", "description"], unique=False)
    # ### end Alembic commands ###
