"""empty message

Revision ID: fec0b00a1636
Revises: ffc9d97c7ddf
Create Date: 2022-05-24 23:18:01.126772

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fec0b00a1636'
down_revision = 'ffc9d97c7ddf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('measure', sa.Column('description', sa.String(length=100), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('measure', 'description')
    # ### end Alembic commands ###
